definer  = {
        'classification':{
            'binary',
            'multiclass',
            'multilabel',
        },
        'regression':{
            'time-series':{
                'one-dimensional-output',
                'multi-dimensional-output',
            },
            'time-independent':{
                'one-dimensional-output',
                'multi-dimensional-output',
            }
        },
        'clustering':{
            'homogeneous',
            'heterogeneous'
        },
        'visuaziation':{
            'supervised':{
                'homogeneous',
                'heterogeneous'
            },
            'unsupervised':{
                'homogeneous',
                'heterogeneous'
            },
        },
    }
